import {StyleSheet} from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: 'white',
    paddingLeft: 5,
    paddingRight: 5,
  },
  logo: {height: 46, width: 162, marginTop: 15},
  heading: {
    color: '#0C1A30',
    fontSize: 25,
    fontWeight: '700',
    lineHeight: 32,
  },
  input: {
    height: 60,
    width: '94%',
    borderRadius: 6,
    backgroundColor: '#FAFAFA',
    // borderWidth: 1,
    marginTop: 10,
    justifyContent: 'center',
  },
  passwordIcon: {height: 16, width: 21},
  buttonStyles: {
    height: 50,
    marginTop: 40,
    width: '94%',
    backgroundColor: '#3669C9',
    borderRadius: 6,
    justifyContent: 'center',
    alignItems: 'center',
  },
  textcolor: {color: 'white'},
  inputpassword: {
    height: 60,
    width: '94%',
    borderRadius: 6,
    backgroundColor: '#FAFAFA',
    // borderWidth: 1,
    marginTop: 10,
    alignItems: 'center',
    justifyContent: 'space-between',
    flexDirection: 'row',
  },
  backicon: {height: 20, width: 10},
  margin10: {marginTop: 10},
  margin40: {marginTop: 40},
  padding10: {padding: 10},
  LineView: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginTop: 10,
  },
  lefttext: {
    fontSize: 16,
    lineHeight: 25,
    color: '#0C1A30',
    marginLeft: 10,
  },
  seemore: {
    fontSize: 12,
    lineHeight: 22,
    color: '#3669C9',
    marginRight: 10,
  },
  listView: {marginLeft: 10, marginRight: 10, elevation: 4},
  card: {width: 155, height: 243},
  LogoView: {
    height: 50,
    width: '100%',
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: 10,
  },
  smalllogo: {width: 90, height: 25},
  cartView: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginRight: 15,
  },
  cart: {width: 22, height: 22, marginRight: 10},
  bell: {width: 20, height: 20},
  searchbar: {paddingLeft: 10, paddingRight: 10, alignSelf: 'center'},
  banner: {height: 180, width: '98%', alignSelf: 'center'},
  slidingview: {height: 230, width: '98%', alignSelf: 'flex-end'},
  LineView2: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginTop: -20,
  },
  listContainer: {margin: 10, height: 58},
  IconView: {marginLeft: 10, marginRight: 10},
  icon: {width: 45, height: 54},
});
